apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerting-rules
  namespace: monitoring
data:
  alerting-rules.yml: |
    groups:
      - name: ai-logs-alerts
        rules:
          - alert: HighAnomalyRate
            expr: rate(app_anomalies_detected_total[5m]) > 0.1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Alta tasa de anomalías detectadas"
              description: "Se están detectando más de 0.1 anomalías por segundo en los últimos 5 minutos"
          
          - alert: HighLatency
            expr: histogram_quantile(0.95, app_log_latency_ms_bucket) > 1000
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Latencia alta en logs"
              description: "El percentil 95 de latencia está por encima de 1000ms"
          
          - alert: APIDown
            expr: up{job="ai-logs-api"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "API no disponible"
              description: "La API de AI Log Analyzer no está respondiendo"
          
          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "Alta tasa de errores HTTP"
              description: "Más del 5% de requests están devolviendo errores 5xx"