apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-anomalies
  namespace: monitoring
data:
  anomalies-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "AI Log Analyzer - Anomalías",
        "tags": ["ai-logs", "anomalies"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Total de Anomalías Detectadas",
            "type": "stat",
            "targets": [
              {
                "expr": "app_anomalies_detected_total",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 5},
                    {"color": "red", "value": 10}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Logs Ingeridos por Minuto",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(app_logs_ingested_total[1m]) * 60",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Latencia de Logs (Percentiles)",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.50, app_log_latency_ms_bucket)",
                "legendFormat": "p50",
                "refId": "A"
              },
              {
                "expr": "histogram_quantile(0.95, app_log_latency_ms_bucket)",
                "legendFormat": "p95",
                "refId": "B"
              },
              {
                "expr": "histogram_quantile(0.99, app_log_latency_ms_bucket)",
                "legendFormat": "p99",
                "refId": "C"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Requests HTTP por Status Code",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total[1m]) * 60",
                "legendFormat": "{{status}} - {{method}} {{path}}",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 16}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }