apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-logs-api
  namespace: ai-logs
  labels: { app: ai-logs-api }
spec:
  replicas: 2
  selector:
    matchLabels: { app: ai-logs-api }
  template:
    metadata:
      labels: { app: ai-logs-api }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: ai-logs-sa
      containers:
        - name: api
          image: 625512666928.dkr.ecr.us-east-1.amazonaws.com/ai-log-analyzer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: ai-logs-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: data
          emptyDir: {}   # demo (efímero). Para persistencia real, usar PVC
